spring:
    jpa:
        database: POSTGRESQL
        show-sql: true
        hibernate.ddl-auto: create
    datasource:
        platform: postgres
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://db/audit
        username: docker
        password: docker
security:
    user:
      name: audit
      password: audit